name: Validate PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  id-token: write
  contents: read

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        shell: bash
        run: npm run lint.check

      - name: Fmt
        shell: bash
        run: npm run fmt.check

      - name: Install Playwright Browsers
        run: npm run setup-playwright

      - name: Test
        shell: bash
        run: npm run test
